import { A8_SLOT_URL, buildAmazonSearchUrl } from "@/lib/site";

export type AffiliateOfferType = "vod" | "ebook" | "hotel" | "product";

export type AffiliatePlacement =
  | "intro"
  | "comparison"
  | "mid_article"
  | "conclusion"
  | "machine_related";

export type AffiliateOffer = {
  id: string;
  provider: string;
  programName: string;
  offerType: AffiliateOfferType;
  serviceName: string;
  href: string;
  ctaLabel: string;
  disclosure: "広告" | "PR";
  isActive: boolean;
  description?: string;
  imageSrc?: string;
};

export const affiliateOffers = {
  soundcoreLiberty4: {
    id: "amazon-soundcore-liberty-4",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "Soundcore Liberty 4",
    href: buildAmazonSearchUrl("Soundcore Liberty 4"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "隣台の爆音がつらいときに。運営者が実際にホールで使用している製品です。",
    imageSrc: "/images/products/soundcore-liberty-4.png",
  },
  soundcoreLiberty5: {
    id: "amazon-soundcore-liberty-5",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "Soundcore Liberty 5",
    href: buildAmazonSearchUrl("Soundcore Liberty 5"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "Anker Japan公式サイトでLiberty 4の後継機として案内されているモデルです。",
    imageSrc: "/images/products/soundcore-liberty-5.png",
  },
  kachikachiKun: {
    id: "amazon-kachikachi-kun",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "カチカチくん（小役カウンター）",
    href: buildAmazonSearchUrl("カチカチくん"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "スイカ・チェリー・ベルなどの小役成立回数を手持ちで数えられるカウンターです。",
  },
  noiseCancellingEarphones: {
    id: "amazon-noise-cancelling-earphones",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "ノイズキャンセリングイヤホン",
    href: buildAmazonSearchUrl("ノイズキャンセリング イヤホン"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
  },
  mobileBatteryCable: {
    id: "amazon-mobile-battery-cable",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "ケーブル内蔵モバイルバッテリー",
    href: buildAmazonSearchUrl("モバイルバッテリー ケーブル内蔵 10000mAh"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "朝一からの長時間実戦でスマホの電池が切れそうなときに。ケーブル内蔵タイプなら荷物も増えにくいです。",
  },
  aSlot: {
    id: "a8-a-slot",
    provider: "A8.net",
    programName: "A8.net",
    offerType: "product",
    serviceName: "家庭で楽しめる中古スロット【A-SLOT】",
    href: A8_SLOT_URL,
    ctaLabel: "A-SLOTを見る",
    disclosure: "広告",
    isActive: true,
    imageSrc: "/images/products/a-slot-banner.gif",
  },
  bookwalkerTokyoGhoul: {
    id: "bookwalker-tokyo-ghoul",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F12565%2F",
    ctaLabel: "BOOK☆WALKERで東京喰種を確認する",
    disclosure: "広告",
    isActive: true,
    description: "『東京喰種トーキョーグール』を電子書籍で確認できます。",
    imageSrc: "/images/products/bookwalker-tokyo-ghoul-banner.jpg",
  },
  mangazenkanTokyoGhoul30: {
    id: "mangazenkan-tokyo-ghoul-30",
    provider: "A8.net",
    programName: "【漫画全巻ドットコム】コミック全巻セット販売",
    offerType: "product",
    serviceName: "漫画全巻ドットコム",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+8BH22A+1892+BW8O2&a8ejpredirect=https%3A%2F%2Fwww.mangazenkan.com%2Fitems%2F10484737%2F",
    ctaLabel: "漫画全巻ドットコムで本編全30巻を確認する",
    disclosure: "広告",
    isActive: true,
    description: "無印14巻と『:re』16巻をまとめた本編全30冊セットです。",
    imageSrc: "/images/products/mangazenkan-tokyo-ghoul-banner.jpg",
  },
  rakutenTokyoGhoul30: {
    id: "rakuten-tokyo-ghoul-30",
    provider: "もしもアフィリエイト",
    programName: "楽天市場の商品購入 / 楽天グループ株式会社",
    offerType: "product",
    serviceName: "楽天市場",
    href: "https://af.moshimo.com/af/c/click?a_id=5721789&p_id=54&pc_id=54&pl_id=616&url=https%3A%2F%2Fsearch.rakuten.co.jp%2Fsearch%2Fmall%2F%25E6%259D%25B1%25E4%25BA%25AC%25E5%2596%25B0%25E7%25A8%25AE%2B%25E5%2585%25A8%25E5%25B7%25BB%2F",
    ctaLabel: "楽天市場で無印14巻＋:re16巻・本編全30巻を確認する",
    disclosure: "広告",
    isActive: false,
    imageSrc: "/images/products/rakuten-banner.gif",
  },
  yahooTokyoGhoul30: {
    id: "yahoo-tokyo-ghoul-30",
    provider: "もしもアフィリエイト",
    programName: "【Yahoo!ショッピング】商品購入",
    offerType: "product",
    serviceName: "Yahoo!ショッピング",
    href: "https://af.moshimo.com/af/c/click?a_id=5721823&p_id=1225&pc_id=1925&pl_id=18502&url=https%3A%2F%2Fshopping.yahoo.co.jp%2Fsearch%3Fp%3D%25E6%259D%25B1%25E4%25BA%25AC%25E5%2596%25B0%25E7%25A8%25AE%2B%25E5%2585%25A8%25E5%25B7%25BB",
    ctaLabel: "Yahoo!ショッピングで無印14巻＋:re16巻・本編全30巻を確認する",
    disclosure: "広告",
    isActive: false,
    imageSrc: "/images/products/yahoo-shopping-banner.jpg",
  },
  rentaTokyoGhoul: {
    id: "valuecommerce-renta-tokyo-ghoul",
    provider: "バリューコマース",
    programName: "Renta!プログラム",
    offerType: "ebook",
    serviceName: "Renta!",
    href: "https://ck.jp.ap.valuecommerce.com/servlet/referral?sid=3777293&pid=892672270&vc_url=https%3A%2F%2Frenta.papy.co.jp%2Frenta%2Fsc%2Ffrm%2Fitem%2F171259%3Fref%3Dvc",
    ctaLabel: "Rentaで東京喰種を確認する",
    disclosure: "広告",
    isActive: true,
    description: "『東京喰種トーキョーグール』をポイント購入で読める電子書籍サービスです。",
    imageSrc: "/images/products/renta-banner.jpg",
  },
  jalanNet: {
    id: "valuecommerce-jalan-net",
    provider: "バリューコマース",
    programName: "★ホテル・宿予約サイト「じゃらんnet」",
    offerType: "hotel",
    serviceName: "じゃらんnet",
    href: "https://ck.jp.ap.valuecommerce.com/servlet/referral?sid=3777293&pid=892672272&vc_url=https%3A%2F%2Fwww.jalan.net%2F",
    ctaLabel: "じゃらんnetで宿を探す",
    disclosure: "広告",
    isActive: true,
    description: "遠征を伴う実践の宿・ホテル予約に使えるサービスです。",
  },
  bookwalkerMonkeyTurn: {
    id: "bookwalker-monkey-turn",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F129091%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでモンキーターンを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『モンキーターン』（河合克敏）を電子書籍で確認できます。",
  },
  mangazenkanMonkeyTurn30: {
    id: "mangazenkan-monkey-turn-30",
    provider: "A8.net",
    programName: "【漫画全巻ドットコム】コミック全巻セット販売",
    offerType: "product",
    serviceName: "漫画全巻ドットコム",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+8BH22A+1892+BW8O2&a8ejpredirect=https%3A%2F%2Fwww.mangazenkan.com%2Fitems%2F1421%2F",
    ctaLabel: "漫画全巻ドットコムで全30巻を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『モンキーターン』の全30巻セットです。",
  },
  bookwalkerSaki: {
    id: "bookwalker-saki",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F2174%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで咲-Saki-を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『咲-Saki-』（小林立）を電子書籍で確認できます。",
  },
  mangazenkanSaki27: {
    id: "mangazenkan-saki-27",
    provider: "A8.net",
    programName: "【漫画全巻ドットコム】コミック全巻セット販売",
    offerType: "product",
    serviceName: "漫画全巻ドットコム",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+8BH22A+1892+BW8O2&a8ejpredirect=https%3A%2F%2Fwww.mangazenkan.com%2Fitems%2F669%2F",
    ctaLabel: "漫画全巻ドットコムで全27巻を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『咲-Saki-』の全27巻セットです。",
  },
  bookwalkerKoukaku: {
    id: "bookwalker-koukaku",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F17303%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで攻殻機動隊を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『攻殻機動隊』（士郎正宗）を電子書籍で確認できます。",
  },
  bookwalkerBakemonogatari: {
    id: "bookwalker-bakemonogatari",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F74662%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで化物語（原作小説）を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作小説『化物語』（西尾維新）を含む＜物語＞シリーズを電子書籍で確認できます。",
  },
  bookwalkerLycorisRecoil: {
    id: "bookwalker-lycoris-recoil",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F389079%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでリコリス・リコイルのコミカライズを確認する",
    disclosure: "広告",
    isActive: true,
    description: "アニメ『リコリス・リコイル』のコミカライズ版を電子書籍で確認できます。",
  },
  bookwalkerHokutoNoKen: {
    id: "bookwalker-hokuto-no-ken",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F43758%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで北斗の拳を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『北斗の拳』（武論尊・原哲夫）を電子書籍で確認できます。",
  },
  amazonGundamSeed: {
    id: "amazon-gundam-seed",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "機動戦士ガンダムSEED",
    href: buildAmazonSearchUrl("機動戦士ガンダムSEED"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "アニメ『機動戦士ガンダムSEED』の関連作品をAmazonで確認できます。",
  },
  bookwalkerGundamUC: {
    id: "bookwalker-gundam-uc",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F14915%2F",
    ctaLabel: "BOOK☆WALKERで機動戦士ガンダムUCを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作小説『機動戦士ガンダムUC』（福井晴敏）を電子書籍で確認できます。",
  },
  bookwalkerTokyoRevengers: {
    id: "bookwalker-tokyo-revengers",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F112843%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで東京卍リベンジャーズを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『東京卍リベンジャーズ』（和久井健）を電子書籍で確認できます。",
  },
  bookwalkerOnePunchMan: {
    id: "bookwalker-one-punch-man",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F70257%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでワンパンマンを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『ワンパンマン』（ONE・村田雄介）を電子書籍で確認できます。",
  },
  bookwalkerKanojoOkarishimasu: {
    id: "bookwalker-kanojo-okarishimasu",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F134131%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで彼女、お借りしますを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『彼女、お借りします』（宮島礼吏）を電子書籍で確認できます。",
  },
  mangazenkanKanojoOkarishimasu45: {
    id: "mangazenkan-kanojo-okarishimasu-45",
    provider: "A8.net",
    programName: "【漫画全巻ドットコム】コミック全巻セット販売",
    offerType: "product",
    serviceName: "漫画全巻ドットコム",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+8BH22A+1892+BW8O2&a8ejpredirect=https%3A%2F%2Fwww.mangazenkan.com%2Fitems%2F10510971%2F",
    ctaLabel: "漫画全巻ドットコムで最新刊までを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『彼女、お借りします』の最新刊までのセットです。",
  },
  bookwalkerGoldenKamuy: {
    id: "bookwalker-golden-kamuy",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F23628%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでゴールデンカムイを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『ゴールデンカムイ』（野田サトル）を電子書籍で確認できます。",
  },
  bookwalkerKaiji: {
    id: "bookwalker-kaiji",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F7863%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで賭博黙示録カイジを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『賭博黙示録カイジ』（福本伸行）を電子書籍で確認できます。",
  },
  bookwalkerKinnikuman: {
    id: "bookwalker-kinnikuman",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F12979%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでキン肉マンを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『キン肉マン』（ゆでたまご）を電子書籍で確認できます。",
  },
  bookwalkerHanmaBaki: {
    id: "bookwalker-hanma-baki",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F5802%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで範馬刃牙を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『範馬刃牙』（板垣恵介）を電子書籍で確認できます。",
  },
  bookwalkerKarakuriCircus: {
    id: "bookwalker-karakuri-circus",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F128989%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでからくりサーカスを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『からくりサーカス』（藤田和日郎）を電子書籍で確認できます。",
  },
  bookwalkerKyokouSuiri: {
    id: "bookwalker-kyokou-suiri",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F55599%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで虚構推理を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『虚構推理』（城平京/片瀬茶柴）を電子書籍で確認できます。",
  },
  bookwalkerKaguyaSama: {
    id: "bookwalker-kaguya-sama",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F66229%2F",
    ctaLabel: "BOOK☆WALKERでかぐや様は告らせたいを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『かぐや様は告らせたい』（赤坂アカ）を電子書籍で確認できます。",
  },
  mangazenkanKaguyaSama28: {
    id: "mangazenkan-kaguya-sama-28",
    provider: "A8.net",
    programName: "【漫画全巻ドットコム】コミック全巻セット販売",
    offerType: "product",
    serviceName: "漫画全巻ドットコム",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+8BH22A+1892+BW8O2&a8ejpredirect=https%3A%2F%2Fwww.mangazenkan.com%2Fitems%2F10341030%2F",
    ctaLabel: "漫画全巻ドットコムで全28巻を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『かぐや様は告らせたい』の全28巻セットです。",
  },
  bookwalkerShamanKing: {
    id: "bookwalker-shaman-king",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F161059%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでシャーマンキングを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『SHAMAN KING』（武井宏之）を電子書籍で確認できます。",
  },
  bookwalkerMushokuTensei: {
    id: "bookwalker-mushoku-tensei",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F11872%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで無職転生を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作小説『無職転生 ～異世界行ったら本気だす～』を電子書籍で確認できます。",
  },
  bookwalkerBasilisk: {
    id: "bookwalker-basilisk",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F364883%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでバジリスク～甲賀忍法帖～を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『バジリスク～甲賀忍法帖～』（山田風太郎/せがわまさき）を電子書籍で確認できます。",
  },
  bookwalkerGoblinSlayer: {
    id: "bookwalker-goblin-slayer",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F83613%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでゴブリンスレイヤーを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『ゴブリンスレイヤー』を電子書籍で確認できます。",
  },
  amazonGodzilla: {
    id: "amazon-godzilla",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "ゴジラ",
    href: buildAmazonSearchUrl("ゴジラ Blu-ray"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "映画『ゴジラ』シリーズの関連作品をAmazonで確認できます。",
  },
  amazonTekken: {
    id: "amazon-tekken",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "鉄拳",
    href: buildAmazonSearchUrl("鉄拳 ゲーム"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "格闘ゲーム『鉄拳』シリーズをAmazonで確認できます。",
  },
  bookwalkerCodeGeass: {
    id: "bookwalker-code-geass",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F276838%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでコードギアス 復活のルルーシュを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『コードギアス 復活のルルーシュ』を電子書籍で確認できます。",
  },
  bookwalkerDumbbell: {
    id: "bookwalker-dumbbell",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F129327%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでダンベル何キロ持てる？を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『ダンベル何キロ持てる？』を電子書籍で確認できます。",
  },
  bookwalkerFireForce: {
    id: "bookwalker-fire-force",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F61854%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで炎炎ノ消防隊を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『炎炎ノ消防隊』（大久保篤）を電子書籍で確認できます。",
  },
  bookwalkerGarei: {
    id: "bookwalker-garei",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F34%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで喰霊を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『喰霊』（瀬川はじめ）を電子書籍で確認できます。",
  },
  amazonGodEater: {
    id: "amazon-god-eater",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "GOD EATER",
    href: buildAmazonSearchUrl("GOD EATER"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "ゲーム『GOD EATER』シリーズの関連作品をAmazonで確認できます。",
  },
  amazonBiohazard: {
    id: "amazon-biohazard",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "バイオハザード",
    href: buildAmazonSearchUrl("バイオハザード"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "ゲーム『バイオハザード』シリーズの関連作品をAmazonで確認できます。",
  },
  amazonMonsterHunter: {
    id: "amazon-monster-hunter",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "モンスターハンターライズ",
    href: buildAmazonSearchUrl("モンスターハンターライズ"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "ゲーム『モンスターハンターライズ』をAmazonで確認できます。",
  },
  amazonDevilMayCry5: {
    id: "amazon-devil-may-cry-5",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "デビル メイ クライ 5",
    href: buildAmazonSearchUrl("デビル メイ クライ 5"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "ゲーム『デビル メイ クライ 5』をAmazonで確認できます。",
  },
  amazonGirlsPanzer: {
    id: "amazon-girls-panzer",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "ガールズ&パンツァー 最終章",
    href: buildAmazonSearchUrl("ガールズ&パンツァー 最終章 Blu-ray"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "アニメ『ガールズ&パンツァー 最終章』のBlu-rayをAmazonで確認できます。",
  },
  amazonBirdieWing: {
    id: "amazon-birdie-wing",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "BIRDIE WING",
    href: buildAmazonSearchUrl("BIRDIE WING Blu-ray"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "アニメ『BIRDIE WING』のBlu-rayをAmazonで確認できます。",
  },
  bookwalkerBofuri: {
    id: "bookwalker-bofuri",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F182099%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで痛いのは嫌なので防御力に極振りしたいと思いますを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『痛いのは嫌なので防御力に極振りしたいと思います。』を電子書籍で確認できます。",
  },
  bookwalkerBandori: {
    id: "bookwalker-bandori",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F214899%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでBanG Dream!バンドリ!のコミックを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミック版『BanG Dream! バンドリ!』を電子書籍で確認できます。",
  },
  bookwalkerAzurLane: {
    id: "bookwalker-azur-lane",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F209908%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでアズールレーンのコミックを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ『アズールレーン びそくぜんしんっ！』を電子書籍で確認できます。",
  },
  bookwalkerMagiaRecord: {
    id: "bookwalker-magia-record",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F195908%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでマギアレコードを確認する",
    disclosure: "広告",
    isActive: true,
    description: "『マギアレコード 魔法少女まどか☆マギカ外伝』を電子書籍で確認できます。",
  },
  amazonMillionLive: {
    id: "amazon-million-live",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "アイドルマスター ミリオンライブ！",
    href: buildAmazonSearchUrl("アイドルマスター ミリオンライブ"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "『アイドルマスター ミリオンライブ！』の関連作品をAmazonで確認できます。",
  },
  amazonTaktOp: {
    id: "amazon-takt-op",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "タクトオーパス",
    href: buildAmazonSearchUrl("タクトオーパス Blu-ray"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "アニメ『タクトオーパス』の関連作品をAmazonで確認できます。",
  },
  bookwalkerArifureta: {
    id: "bookwalker-arifureta",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F99891%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでありふれた職業で世界最強を確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『ありふれた職業で世界最強』を電子書籍で確認できます。",
  },
  bookwalkerSymphogear: {
    id: "bookwalker-symphogear",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F8078%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで戦姫絶唱シンフォギアを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『戦姫絶唱シンフォギア』を電子書籍で確認できます。",
  },
  bookwalkerKabaneri: {
    id: "bookwalker-kabaneri",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F94529%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで甲鉄城のカバネリを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『甲鉄城のカバネリ』を電子書籍で確認できます。",
  },
  bookwalkerLupin: {
    id: "bookwalker-lupin",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F58175%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでルパン三世を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『ルパン三世』（モンキー・パンチ）を電子書籍で確認できます。",
  },
  bookwalkerInitialD: {
    id: "bookwalker-initial-d",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F4358%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで頭文字Dを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『頭文字D』（しげの秀一）を電子書籍で確認できます。",
  },
  bookwalkerNanatsuNoMaken: {
    id: "bookwalker-nanatsu-no-maken",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F222012%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで七つの魔剣が支配するを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『七つの魔剣が支配する』を電子書籍で確認できます。",
  },
  bookwalkerTenseiKen: {
    id: "bookwalker-tensei-ken",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F112059%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで転生したら剣でしたを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『転生したら剣でした』を電子書籍で確認できます。",
  },
  bookwalkerTenseiOujo: {
    id: "bookwalker-tensei-oujo",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F285398%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで転生王女と天才令嬢の魔法革命を確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『転生王女と天才令嬢の魔法革命』を電子書籍で確認できます。",
  },
  bookwalkerRezero: {
    id: "bookwalker-rezero",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F11978%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでRe:ゼロから始める異世界生活を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作小説『Re:ゼロから始める異世界生活』を電子書籍で確認できます。",
  },
  bookwalkerSeishunButaYaro: {
    id: "bookwalker-seishun-buta-yaro",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F87088%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで青春ブタ野郎はバニーガール先輩の夢を見ないを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『青春ブタ野郎はバニーガール先輩の夢を見ない』を電子書籍で確認できます。",
  },
  bookwalkerSeiya: {
    id: "bookwalker-seiya",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F13133%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで聖闘士星矢を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『聖闘士星矢』（車田正美）を電子書籍で確認できます。",
  },
  bookwalkerIkkiTousen: {
    id: "bookwalker-ikki-tousen",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F151508%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで一騎当千を確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『一騎当千／真・一騎当千』（塩崎雄二）を電子書籍で確認できます。",
  },
  amazonOnimusha: {
    id: "amazon-onimusha",
    provider: "Amazon",
    programName: "Amazonアソシエイト",
    offerType: "product",
    serviceName: "鬼武者",
    href: buildAmazonSearchUrl("鬼武者"),
    ctaLabel: "Amazonで探す",
    disclosure: "広告",
    isActive: true,
    description: "ゲーム『鬼武者』シリーズをAmazonで確認できます。",
  },
  bookwalkerValvrave: {
    id: "bookwalker-valvrave",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F15097%2Flist%2F",
    ctaLabel: "BOOK☆WALKERで革命機ヴァルヴレイヴのコミックを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『革命機ヴァルヴレイヴ 裏切りの烙印』を電子書籍で確認できます。",
  },
  bookwalkerToaruIndex: {
    id: "bookwalker-toaru-index",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F2157%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでとある魔術の禁書目録を確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『とある魔術の禁書目録』を電子書籍で確認できます。",
  },
  bookwalkerToaruRailgun: {
    id: "bookwalker-toaru-railgun",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F1971%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでとある科学の超電磁砲を確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『とある科学の超電磁砲』を電子書籍で確認できます。",
  },
  bookwalkerToLoveRu: {
    id: "bookwalker-to-love-ru",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F12996%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでToLOVEるダークネスを確認する",
    disclosure: "広告",
    isActive: true,
    description: "原作漫画『To LOVEる―とらぶる―ダークネス』（矢吹健太朗）を電子書籍で確認できます。",
  },
  bookwalkerDarlingFranxx: {
    id: "bookwalker-darling-franxx",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F149000%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでダーリン・イン・ザ・フランキスを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『ダーリン・イン・ザ・フランキス』を電子書籍で確認できます。",
  },
  bookwalkerWatashiNoShiawase: {
    id: "bookwalker-watashi-no-shiawase",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F219008%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでわたしの幸せな結婚を確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『わたしの幸せな結婚』を電子書籍で確認できます。",
  },
  bookwalkerYokoso: {
    id: "bookwalker-yokoso",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F153491%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでようこそ実力至上主義の教室へを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『ようこそ実力至上主義の教室へ』を電子書籍で確認できます。",
  },
  bookwalkerZombielandSaga: {
    id: "bookwalker-zombieland-saga",
    provider: "A8.net",
    programName: "215万冊以上から探す！初回購入で50%還元【BOOK WALKER】",
    offerType: "ebook",
    serviceName: "BOOK☆WALKER",
    href: "https://px.a8.net/svt/ejp?a8mat=4B8DGU+89OR8Y+5X16+BW8O2&a8ejpredirect=https%3A%2F%2Fbookwalker.jp%2Fseries%2F252857%2Flist%2F",
    ctaLabel: "BOOK☆WALKERでゾンビランドサガを確認する",
    disclosure: "広告",
    isActive: true,
    description: "コミカライズ版『ゾンビランドサガ サガ覚醒編』を電子書籍で確認できます。",
  },
} as const satisfies Record<string, AffiliateOffer>;

export type AffiliateOfferId = keyof typeof affiliateOffers;

export function getActiveAffiliateOffer(id: AffiliateOfferId | string): AffiliateOffer | null {
  const offer = affiliateOffers[id as AffiliateOfferId];
  return offer?.isActive ? offer : null;
}
